spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
#        use-new-id-generator-mappings: false
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: validate
        hbm2ddl: validate
  h2:
    console:
      enabled: true

  flyway:
    enabled: true
